name: Erlang CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '27'
          rebar3-version: '3'
      - name: Compile
        run: rebar3 compile
      - name: EUnit
        run: rebar3 eunit
